### ISSUE TITLE
Use TypeScript better

### ISSUE THREAD

**Issue by youngjae99** [youngjae99/Bvent#50]
### Intro
TypeScript의 장점을 극대화 하기 위해 최대한 Bvent Frontend Code에서 사용하고 있는 any를 제외하고 interface를 

### ToDos
- [ ] strict 옵션 적용
- [ ] 변수와 함수에 any, 타입 단언(as, !)을 모두 없애기
- [ ] 반복되는 타입은 제네릭, 타입 상속 / 합성 등으로 추상화
- [ ] 보다 좁은 타입으로 정의 (ex. string -> as const or union)

### References
- [https://www.typescriptlang.org/docs/handbook/2/basic-types.html](https://www.typescriptlang.org/docs/handbook/2/basic-types.html) (타입스크립트 공식문서)
- https://typescript-kr.github.io/ (타입스크립트 핸드북)
- [https://ts-error-translator.vercel.app/](https://ts-error-translator.vercel.app/) (타입스크립트 에러 번역기)
- [https://react-typescript-cheatsheet.netlify.app/docs/advanced/types_react_api#typesreact](https://react-typescript-cheatsheet.netlify.app/docs/advanced/types_react_api#typesreact) (타입스크립트 Cheat Sheet)
- [https://github.com/type-challenges/type-challenges/blob/main/README.ko.md](https://github.com/type-challenges/type-challenges/blob/main/README.ko.md) (타입스크립트 고급 타입 활용법을 익혀볼 수 있는 퀴즈)
- [http://www.kyobobook.co.kr/product/detailViewKor.laf?mallGb=KOR&ejkGb=KOR&barcode=9788966263134](http://www.kyobobook.co.kr/product/detailViewKor.laf?mallGb=KOR&ejkGb=KOR&barcode=9788966263134) (댄 밴더캄 - 이펙티브 타입스크립트)
- [https://yceffort.kr/2021/05/ast-for-javascript](https://yceffort.kr/2021/05/ast-for-javascript) (자바스크립트 개발자를 위한 AST 이해하기)
- [https://transform.tools/json-to-typescript](https://transform.tools/json-to-typescript) (JSON 객체로부터 타입을 자동 생성)
